[project]
name = "Exonize"
description = "Find duplicated exons"
authors = [
	"Marina Herrera Sarrias <marina.sarrias_at_math.su.se>",
	"Lars Arvestad <arvestad_at_math.su.se>",
	"Liam Longo <llongo_at_elsi.jp>"
]
maintainers = [
	"Marina Herrera Sarrias <marina.sarrias_at_math.su.se>",
	"Lars Arvestad <arvestad_at_math.su.se>"
]
version = "0.1"
dependencies = [
	     "gffutils>=0.11.1",
	     "tqdm>=4.65.0",
	     "portion>=2.4.0",
	     "biopython>=1.81",
]
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project.scripts]
exonize = "exonize.exonize:main"